# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ../:/var/www
            - ./logs/nginx:/var/log/nginx
        networks:
          crypto:
            aliases:
               - eth.explorer.local
        # nginx должен общаться с php контейнером
        links:
            - php
#            - bitcoind
        #container_name: local_nginx
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        user: "1000:1000"
        # монтируем директорию с проектами
        volumes:
            - ../:/var/www
        links:
            - postgres
        networks:
            - crypto
        #container_name: local_php
    postgres:
        image: postgres:14.3
#        restart: always
        logging:
          options:
            max-size: 10m
            max-file: "3"
        environment:
          POSTGRES_DB: "cryptomus"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
          - "5432:5432"
        networks:
          - crypto
        volumes:
          - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
          - data_postgres:/var/lib/postgresql
    redis:
        image: redis:6.2-alpine
        ports:
          - '6379:6379'
        volumes:
          - ./data/redis:/data
        networks:
          - crypto
        command: redis-server --save 20 1 --loglevel warning --requirepass 1111
volumes:
    data_postgres:
    bitcoin-data:
#        driver_opts:
#            device: tmpfs
#            type: tmpfs
#            o: "size=5000m"   
networks:
    crypto:
